### PR TITLE
Added more options to sniff command

### PR DESCRIPTION
**Pull request by freezysko**

### CODE REVIEW

**Comment by brodkin** [comment]
I've actually wanted to include some more flags in the project but haven't had time. My only concern is as follows:

Is this the best way to get the job done? If we're going to support specific flags then we also need to limit the version of the CLI app via composer. Currently any stable version is acceptable. 

I think it would be preferable to pass all flags not implemented by this project to the CLI tool rather than implementing the flags manually. Thoughts?

If we do include your PR it will need tests built to verify that the flags operate as expected.

**Comment by Stolz** [comment]
Please do not include more flags. IMHO hardcoding parameters is not a good idea . i.e: the --tab-wit=4 is giving me headaches and currently I have no way to get rid of it. Currently instead of the artisan command I'm runing `./vendor/bin/phpcs app --standard=app/phpcs.xml --my-parameters` because of this matter.

The only hardcoded parameters should be those which make sense for every Laravel installation and are always mandatory but even that, they should still be able to be overridden by command line.

If you accept a suggestion, take a look at how I handle this in my [SchemaSpy](https://github.com/Stolz/laravel-schema-spy/blob/master/src/Stolz/SchemaSpy/Command.php#L83) package. It hardcodes only the mandatory parameters but they can still be overriden with a config file. A sample config file with sensible defaults can be included with "config:publish" so the user is free to add custom parameters. This also makes the artisan command more flexible for future changes because is the user who controls the parameters, not the package.

**Comment by brodkin** [comment]
You're right. I wasn't suggesting that flags should be hard-coded--quite the opposite actually. In terms of the `--tab-width` flag I think it is a necessary evil since it cannot be set via PHPCS's xml configuration. Thankfully your implementation seems to address that nicely by setting a default and allowing it to be overridden. I might consider adding a config file but I would hate to implement that when it would currently only contain one item.

My hesitation about this PR relates to manually adding flags like `--report` since there is no need to provide a default for those items. What I have wanted to investigate is if there is a way to allow the passthru of all undefined arguments directly to the CLI so that we don't have to implement or update flags in this project every time that PHPCS gets updated. Do you have any knowledge in this area?

For now I'm willing to merge the code related to `--tab-width` but I'd like to hold off on the rest to see if there is a better solution.

**Comment by freezysko** [comment]
My first shot was to update this command to passthru every option to PHPCS because I don't like when it's hardcoded but I found that it can't be done. Laravel needs to have options predefined because it uses `Symfony\Component\Console\Input\Input` which is checking if options are defined in `Symfony\Component\Console\Input\ArgvInput`.

``` php
private function addLongOption($name, $value)
{
    if (!$this->definition->hasOption($name)) {
        throw new \RuntimeException(sprintf('The "--%s" option does not exist.', $name));
    }
}
```

Laravel also uses predefined options to provide help informations when you call `php artisan help inspect:sniff`

**Comment by brodkin** [comment]
That's what I had feared. If that is the case then we need to limit the version of PHPCS to the current major version to ensure compatability. Honestly that is a good idea anyway because I hear that there are some major changes coming down the pipe in the that project.

If you can update the PR that would be great but I can do it if not. It will probably just take me longer.

**Comment by freezysko** [comment]
yes there are some major changes in PHP_CodeSniffer but they will be in version 2.0 and right now this library requires `"squizlabs/php_codesniffer": "~1.4"` which means >= 1.4 && < 2.0 so we are safe and you can merge this PR ;)

**Comment by brodkin** [comment]
Sorry, I'm dumb. I forgot that I changed that in the last update. All of the packages used to use a `@stable` version requirement.

I'll do a final review of the code and should have a new release ready by Tuesday.

**Pull request merged**
